version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3.8.5-alpine
    logging:
      driver: none

  celery:
    build: .
    depends_on:
      - rabbitmq
    volumes:
      - .:/app

  flower:
    build: .
    depends_on:
      - rabbitmq
      - celery
    ports:
      - 5555:5555
    command: celery flower -A tasks --loglevel=info
    volumes:
      - .:/app
