version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3.8.5-alpine
    logging:
      driver: none

  cron:
    build: ./jobs
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  celery:
    build: .
    environment:
      WEBHOOK_URL: ${WEBHOOK_URL}
    depends_on:
      - rabbitmq
    volumes:
      - .:/app

  flower:
    build: .
    depends_on:
      - rabbitmq
    command: flower -A dailytasks --port=5555
    volumes:
      - .:/app
